=== allometry/Apothecary/apothecary.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="name">
    <xs:complexType mixed="true" />
  </xs:element>

  <xs:element name="potion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="primaryIngredient" />
        <xs:element ref="secondaryIngredient" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="potions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="potion" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="primaryIngredient">
    <xs:complexType mixed="true">
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="secondaryIngredient">
    <xs:complexType mixed="true">
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== allometry/Apothecary/apothecary.xml
<?xml version="1.0" encoding="UTF-8"?>
<potions xmlns="http://scripts.allometry.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://scripts.allometry.com/app/webroot/xml/apothecary.xsd">
	<potion>
		<name>Attack Potion</name>
		<primaryIngredient name="Guam Leaf">0000</primaryIngredient>
		<secondaryIngredient name="Eye of Newt">0000</secondaryIngredient>
		<level>3</level>
	</potion>
	<potion>
		<name>Antipoison</name>
		<primaryIngredient name="Marrentill">0000</primaryIngredient>
		<secondaryIngredient name="Unicorn Horn Dust">0000</secondaryIngredient>
		<level>5</level>
	</potion>
	<potion>
		<name>Relicym's Balm</name>
		<primaryIngredient name="Rogue's Purse">0000</primaryIngredient>
		<secondaryIngredient name="Snakeweed">0000</secondaryIngredient>
		<level>8</level>
	</potion>
	<potion>
		<name>Strength Potion</name>
		<primaryIngredient name="Tarromin">0000</primaryIngredient>
		<secondaryIngredient name="Limpwurt Root">0000</secondaryIngredient>
		<level>12</level>
	</potion>
	<potion>
		<name>Serum 207</name>
		<primaryIngredient name="Tarromin">0000</primaryIngredient>
		<secondaryIngredient name="Ashes">0000</secondaryIngredient>
		<level>15</level>
	</potion>
	<potion>
		<name>Restore Potion</name>
		<primaryIngredient name="Harralander">0000</primaryIngredient>
		<secondaryIngredient name="Red Spider Eggs">0000</secondaryIngredient>
		<level>22</level>
	</potion>
	<potion>
		<name>Energy Potion</name>
		<primaryIngredient name="Harralander">0000</primaryIngredient>
		<secondaryIngredient name="Chocolate Dust">0000</secondaryIngredient>
		<level>26</level>
	</potion>
	<potion>
		<name>Defense Potion</name>
		<primaryIngredient name="Ranarr Weed">0000</primaryIngredient>
		<secondaryIngredient name="Whiteberries">0000</secondaryIngredient>
		<level>30</level>
	</potion>
	<potion>
		<name>Agility Potion</name>
		<primaryIngredient name="Toadflax">0000</primaryIngredient>
		<secondaryIngredient name="Toad's Legs">0000</secondaryIngredient>
		<level>34</level>
	</potion>
	<potion>
		<name>Combat Potion</name>
		<primaryIngredient name="Harralander">0000</primaryIngredient>
		<secondaryIngredient name="Ground Goat's Horn">0000</secondaryIngredient>
		<level>36</level>
	</potion>
	<potion>
		<name>Prayer Potion</name>
		<primaryIngredient name="Ranarr Weed">0000</primaryIngredient>
		<secondaryIngredient name="Snape Grass">0000</secondaryIngredient>
		<level>38</level>
	</potion>
</potions>
